add tutorial notebooks conversion to onnx
dianna-ai/dianna pull request #176
Opened 2022-01-28 15:00 UTC by geek-yang

- Add tutorial notebooks about conversions from pytorch/tensorflow/keras/sklearn to onnx
- Add `requirements.txt` to list all the dependencies for notebooks about conversions

2022-01-31 16:06 UTC, egpbos commented
Is this ready for review?

2022-02-01 13:24 UTC, geek-yang commented
Note that the `keras2onnx` notebook is slightly different from the one in the `dianna.exploration` repo. The old notebook uses `keras2onnx` package to convert `keras` model to `onnx` format. But the development of [`keras2onnx`](https://github.com/onnx/keras-onnx) has been stopped and the authors redirect all the users to `tf2onnx` package. Now we use `tf2onnx` package to do the conversion.

2022-02-01 13:40 UTC, geek-yang commented
resnet files ([`resnet_savedmodel.onnx`](https://github.com/dianna-ai/dianna/blob/127-notebook-conversion-onnx/tutorials/models/resnet_savedmodel.onnx and [`resnet_savedmodel` folder](https://github.com/dianna-ai/dianna/tree/127-notebook-conversion-onnx/tutorials/models/resnet_savedmodel))) are saved to pass the test for notebooks. However, these two files are too large (over ~100 MB each). Shall we remove the files and skip the test for the related code blocks?

2022-02-01 13:42 UTC, geek-yang commented on tutorials/conversion_onnx/keras2onnx.ipynb
> +    "onnx_savedmodel = '../models/resnet_savedmodel.onnx'\n",
This is the code which requires the model. Is it possible to skip the test only for this line in the notebook?

2022-02-01 13:43 UTC, geek-yang commented on tutorials/conversion_onnx/keras2onnx.ipynb
> +    "savedmodel_dir = '../models/resnet_savedmodel'\n",
Same here.

2022-02-01 14:04 UTC, loostrum commented
> resnet files ([`resnet_savedmodel.onnx`](https://github.com/dianna-ai/dianna/blob/127-notebook-conversion-onnx/tutorials/models/resnet_savedmodel.onnx and [`resnet_savedmodel` folder](https://github.com/dianna-ai/dianna/tree/127-notebook-conversion-onnx/tutorials/models/resnet_savedmodel))) are saved to pass the test for notebooks. However, these two files are too large (over ~100 MB each). Shall we remove the files and skip the test for the related code blocks?

That explains why I suddenly had to download 180 MB when updating my copy of the repo :P 
I'm a bit surprised we have to store the models manually. Sure the converter might need to store it, but it should automatically download and use the keras builtin resnet. 

In any case I'd vote for removing the models (do check how to remove them completely from git history, otherwise they'll remain in the repo unless you do a shallow clone), and skipping (part of) the notebook if required

2022-02-01 14:16 UTC, geek-yang commented
> > resnet files ([`resnet_savedmodel.onnx`](https://github.com/dianna-ai/dianna/blob/127-notebook-conversion-onnx/tutorials/models/resnet_savedmodel.onnx and [`resnet_savedmodel` folder](https://github.com/dianna-ai/dianna/tree/127-notebook-conversion-onnx/tutorials/models/resnet_savedmodel))) are saved to pass the test for notebooks. However, these two files are too large (over ~100 MB each). Shall we remove the files and skip the test for the related code blocks?
> 
> That explains why I suddenly had to download 180 MB when updating my copy of the repo :P I'm a bit surprised we have to store the models manually. Sure the converter might need to store it, but it should automatically download and use the keras builtin resnet.
> 
> In any case I'd vote for removing the models (do check how to remove them completely from git history, otherwise they'll remain in the repo unless you do a shallow clone), and skipping (part of) the notebook if required

@loostrum I couldn't agree more. We'd better move the large models as they make the repo too heavy...I need to figure out how to skip part of the test (if not possible, then the whole test for the keras conversion notebook). Any one has a quick solution to it?

2022-02-01 14:49 UTC, geek-yang commented
> Is this ready for review?

Yes, it is now!

2022-02-01 15:20 UTC, geek-yang commented
We can skip cells by throwing an exception (https://github.com/treebeardtech/nbmake). Need to test it.

2022-02-02 15:26 UTC, egpbos requested changes
Looks very good to me!

One final change I'd like to see is the `../models/` parts of file paths removed in `keras2onnx.ipynb` and `tensorflow2onnx.ipynb`. These are only sensible when running Jupyter from within the tutorials folder, which not everybody may do, so I would just remove the path and just stick to bare filenames, then people can pick their own working directory (= data dumping directory).

2022-02-02 15:54 UTC, geek-yang commented
> Looks very good to me!
> 
> One final change I'd like to see is the `../models/` parts of file paths removed in `keras2onnx.ipynb` and `tensorflow2onnx.ipynb`. These are only sensible when running Jupyter from within the tutorials folder, which not everybody may do, so I would just remove the path and just stick to bare filenames, then people can pick their own working directory (= data dumping directory).
> 
> Feel free to merge after that, if nobody else objects ;)

Thanks for your comment @egpbos , and your help with the test :) I will remove the `../models/` parts. It is not necessary, I agree.

2022-02-02 15:57 UTC, egpbos approved these changes

2022-02-02 16:23 UTC, merged