added high level overview to readme
dianna-ai/dianna pull request #178
Opened 2022-01-31 15:53 UTC by egpbos

Fixes #137

2022-01-31 16:05 UTC, elboyran commented
Some checks are not passing, is it ready for review?

2022-02-01 14:21 UTC, loostrum approved these changes
I like it! Short and to the point, which is great for potential users

2022-02-01 14:45 UTC, elboyran requested changes
As you noticed already, it now overlaps with what's under Why DIANNA below (after merging #177). I propose we leave one sentence (merging first and last bullet points as I didn't mention them in #177) and add informative image possibly with 1 sentence.

2022-02-01 14:51 UTC, elboyran approved these changes

2022-02-01 15:05 UTC, merged