added time-series example to readme
dianna-ai/dianna pull request #659
Opened 2023-11-08 11:04 UTC by cpranav93

Adds a time-series example to the readme.

Visualization is not shown in example due to its complexity. The users are referred to the tutorial for an example there.

Closes #647

2023-11-13 09:20 UTC, cwmeijer requested changes
Looks great! Good call to add a link to a tutorial!

2023-11-14 09:39 UTC, cpranav93 commented on README.md
> +labels = np.argsort(class_names) # The list of labels for different classes.
I believe the difference between the class_names and labels is not about the complete list and the interesting list but rather the string names in class_names and corresponding integers in labels. Would this make it clearer:
```suggestion
Which of your model's classes do you want an explanation for?

```python
class_names= [class_a, class_b] # String representation of the different classes of interest
labels = np.argsort(class_names) # Numerical representation of the different classes of interest for the model
```

2023-11-14 09:39 UTC, cpranav93 commented on README.md
> +num_slices = len(timeseries_instance) # The number of slices to divide the time series data into.
I am discussing with Yang about the necessity for num_slices. It is currently there in the input argument but is not used anywhere in the function.

2023-11-21 10:28 UTC, cwmeijer approved these changes
Much better! Thanks!

2023-11-22 14:44 UTC, merged