add rise tabular
dianna-ai/dianna pull request #730
Opened 2024-03-20 09:48 UTC by cwmeijer

Fixes #644 . WIP.

2024-05-30 18:29 UTC, elboyran commented on dianna/utils/maskers.py
> +        yield np.random.choice(
maybe check this auto suggestion

2024-06-07 13:55 UTC, elboyran requested changes
Nice work. I left some minor comments before.

2024-06-13 08:21 UTC, cwmeijer commented on dianna/utils/maskers.py
>      """Generate masks that masks complete time steps at a time while masking time steps in a segmented fashion.
I updated the docstring. It's better now I think.

2024-06-14 11:37 UTC, elboyran approved these changes
Nice!

2024-06-19 09:13 UTC, merged