Add a tutorial notebook for emulator use case
dianna-ai/dianna pull request #811
Opened 2024-06-26 09:50 UTC by SarahAlidoost

closes #803

2024-08-08 15:05 UTC, cwmeijer requested changes
Great work! This is a really nice notebook with a great story! Thanks a lot for the work you put in to this. I added my comments in reviewNB with suggestions for some minor improvements.

2024-08-13 09:34 UTC, SarahAlidoost commented
> Great work! This is a really nice notebook with a great story! Thanks a lot for the work you put in to this. I added my comments in reviewNB with suggestions for some minor improvements.

thanks for reviewing. I checked the [reviewNB of this pull request](https://app.reviewnb.com/dianna-ai/dianna/pull/811/discussion/) and couldn't find any comments :thinking: Can you please send me a link to your comments?

2024-08-14 10:07 UTC, cwmeijer approved these changes

2024-08-26 08:00 UTC, SarahAlidoost commented
I addressed comments from @cwmeijer and @elboyran . The failing tests in github actions are due to #842

2024-08-26 08:00 UTC, merged