818 dashboard modifu input data section for multiple examples
dianna-ai/dianna pull request #831
Opened 2024-07-31 08:11 UTC by laurasootes

This PR a specifications for each example in the dashboard in the left menu (fixes #818).
Additionally, upon example selection, text will be shown explaining what the example is (adds to #816 and #819)

Please check if the explanatory text is sufficient.

2024-08-01 13:55 UTC, SarahAlidoost commented on dianna/dashboard/pages/Time_series.py
> +        """)
```suggestion
    st.markdown(
        """This example demonstrates the use of DIANNA
        on a pre-trained binary classification model for season prediction. The
        input data is the [weather prediction
        dataset](https://zenodo.org/records/5071376). This classification model
        uses time (days) as function of mean temperature to predict if the whole
        time series is either summer or winter. Using a chosen XAI method the
        relevance scores are displayed on top of the timeseries. The days
        contributing positively towards the classification decision are
        indicated in red and those who contribute negatively in blue.
        """)
```

2024-08-01 13:56 UTC, SarahAlidoost commented on dianna/dashboard/pages/Time_series.py
> +        """)
fixing ruff error on `Line too long`

2024-08-01 13:57 UTC, SarahAlidoost commented on dianna/dashboard/pages/Text.py
> +        [Stanford Sentiment Treebank dataset](https://nlp.stanford.edu/sentiment/index.html) which contains one-sentence movie reviews. A pre-trained neural network classifier is used, which identifi
```suggestion
        """
        This example demonstrates the use of DIANNA on the [Stanford Sentiment
        Treebank dataset](https://nlp.stanford.edu/sentiment/index.html) which
        contains one-sentence movie reviews. A pre-trained neural network
        classifier is used, which identifies whether a movie review is positive
        or negative.
```

2024-08-01 13:57 UTC, SarahAlidoost commented on dianna/dashboard/pages/Text.py
> +        [Stanford Sentiment Treebank dataset](https://nlp.stanford.edu/sentiment/index.html) which contains one-sentence movie reviews. A pre-trained neural network classifier is used, which identifi
fixing ruff error on `Line too long`

2024-08-01 13:58 UTC, SarahAlidoost commented on dianna/dashboard/pages/Images.py
> +        """
```suggestion
        """
        This example demonstrates the use of DIANNA on a pretrained binary
        [MNIST](https://yann.lecun.com/exdb/mnist/) model using a hand-written
        digit images. The model predict for an image of a hand-written 0 or 1,
        which of the two it most likely is. This example visualizes the
        relevance attributions for each pixel/super-pixel by displaying them on
        top of the input image.
        """
```

2024-08-01 13:58 UTC, SarahAlidoost commented on dianna/dashboard/pages/Images.py
> +        """
fixing ruff error on `Line too long`

2024-08-01 14:06 UTC, SarahAlidoost requested changes
@laurasootes thanks for adding clear explanations for each example :1st_place_medal: . Some text used in `test_dashboard.py` should be changed accordingly, for example [this one](https://github.com/dianna-ai/dianna/blob/430be09d51c26cfc5fc7ed9b87126cb7965a544b/tests/test_dashboard.py#L101). 

Also, I noticed a title is set for each page as `st.title('Image explanation')` or `st.title('Time series explanation')`, .... Can we make them more informative? :thinking: 

I fixed some `line too long` errors, but let's check if there are other linter errors. Can you please run `ruff check` on the changed files?

2024-08-06 13:51 UTC, laurasootes commented
hi @SarahAlidoost, thanks for your review. I updated the dashboard tests accordingly and checked the line lengths, after your fixes they are all good now. 

I agree with your comment about the page title. I have added it to issue #816 where in which all tetx-related tihings will be updated

2024-08-07 09:20 UTC, SarahAlidoost approved these changes
@laurasootes thanks for addressing the comments. Changes look good :+1:  Before merging, can you please change the base branch of this pull request from `817-dashboard-move-menu` to `main`. Because #830 is already merged. Also, only after changing the base to `main`, github action will run automatically on this pull request.

2024-08-07 10:08 UTC, merged