Update CONTEXT.md
dianna-ai/dianna pull request #846
Opened 2024-08-23 13:11 UTC by elboyran

Why DIANNA in the documentation was obsolete.

2024-08-23 13:14 UTC, elboyran commented
No idea, why the link checker thinks the TF link is dead- it isn't.

2024-09-05 13:21 UTC, cwmeijer requested changes
Nice update indeed. I have some recommendation about the dashboard description, not being in a state for a user to work with their own model and/or data.

2024-09-05 13:21 UTC, cwmeijer commented on docs/CONTEXT.md
> +DIANNA provided a simle unified interface to the chosen XAI methods (explainers). The library can be used both from the command-line and from its easy to use [dashboard](https://github.com/dianna-ai/
The dashboard is not ready to be used as an interface to DIANNA. It is merely a very cool demo tool at this point.
```suggestion
DIANNA provided a simple unified interface to the chosen XAI methods (explainers). The library can be used both from the command-line and we are working on an easy to use [dashboard](https://github.com/dianna-ai/dianna/tree/main?tab=readme-ov-file#dashboard), which can already be run with some of our examples for demo purposes.
```

2024-09-05 13:21 UTC, cwmeijer commented on docs/CONTEXT.md
> +Most libraries support at most 2 modalities: images and text. While DIANNA has also started with these two, now it also supports time series and tabular data with embeddings beging work in progress.
```suggestion
Most libraries support at most 2 modalities: images and text. While DIANNA has also started with these two, now it also supports time series and tabular data with embeddings being work in progress. 
```

2024-09-05 13:21 UTC, cwmeijer commented on docs/CONTEXT.md
> +To demonstrate the usefulness and enable studying the properties of the relevances on an intuitive level, DIANNA comes with new and exsisting [datasets](https://github.com/dianna-ai/dianna/tree/main?
```suggestion
To demonstrate the usefulness and enable studying the properties of the relevances on an intuitive level, DIANNA comes with new and existing [datasets](https://github.com/dianna-ai/dianna/tree/main?tab=readme-ov-file#datasets) and [models](https://github.com/dianna-ai/dianna/tree/main?tab=readme-ov-file#onnx-models) for both classification and regression tasks for image, text, time series and tabular data.
```

2024-09-11 08:29 UTC, cwmeijer approved these changes
👍

2024-09-11 09:57 UTC, elboyran commented
It also depends on the outcome of #848.

2024-09-11 10:04 UTC, merged