Update README.md
dianna-ai/dianna pull request #868
Opened 2024-11-07 13:50 UTC by elboyran

Added link to the RSD page for the explainable embedding software.

2024-11-07 15:08 UTC, elboyran commented
I've also updated the [RSD software page](https://research-software-directory.org/software/dianna).

2024-11-07 15:28 UTC, elboyran commented
Updated [documentation link](https://dianna.readthedocs.io/en/link2explainable-embeddings/)

2024-11-11 10:04 UTC, cwmeijer requested changes
Thanks for adding the link! I corrected the link to the repo and did a textual suggestion.

2024-11-11 10:04 UTC, cwmeijer commented on README.md
> +| Embedding  | *modified RISE in [Explainable embeddings package](https://github.com/dianna-ai/explainable_embedding)  |                                                                     |
```suggestion
| Embedding  | *inspired by RISE in [distance_explainer](https://github.com/dianna-ai/distance_explainer)  |                                                                     |                                                                                                     |
```

2024-11-11 10:04 UTC, cwmeijer commented on docs/ROADMAP.md
> +- Extend the dashboard with more examples and make it to work smoothly with custom data and models
```suggestion
- Extend the dashboard with more examples and make it work with custom data and models
```

2024-11-12 10:05 UTC, cwmeijer commented on README.md
> + *   Supports images, text, time series, tabular data modalities and embeddings (in a related [package](https://github.com/dianna-ai/explainable_embedding))
```suggestion
 *   Supports images, text, time series, tabular data modalities and embeddings (in a related package, [distance_explainer](https://github.com/dianna-ai/distance_explainer)
```

2024-11-12 10:07 UTC, cwmeijer approved these changes
I saw one more link that needed updating to our distance_explainer repo. Please commit that one as well before merging.
Thanks for this PR!

2024-11-13 09:55 UTC, merged